<head>
	<title><?php echo $this->moo; ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo Router::getUrl('file:style.css'); ?>" />
</head>

<body>
	<?php echo $this->_content; ?>
	<img src="<?php echo Router::getUrl('file:image1.jpg'); ?>" alt="picture here" /><br /><br />
	<a href="<?php echo Router::getUrl('app:Foo'); ?>">Link example #1</a><br /><br />
	<?php Renderer::partial('view/dbgrid.phtml', array('rows' => $this->rows)) ?>
</body>
